name: my-first-workflow

on: workflow_dispatch

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greetings
        run: echo "Hello there!"
      - name: Print GoodBye
        run: echo "goodbye.. see you again"
      - name: Test mutiline
        run: |
          echo "First output"
          echo "Second output"
